[project]
name = "langchain-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.1",
    "langchain>=1.4.1",
    "langchain-classic>=1.0.8",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.18",
    "langchain-text-splitters>=1.1.2",
    "langchain-unstructured>=1.0.1",
    "langchainhub>=0.1.21",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.4",
    "tiktoken>=0.14.0",
    "unstructured>=0.27.8",
]

[project.scripts]
langchain-course = "langchain_course:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
# Exclude packages published in the last 7 days
exclude-newer = "7d"
